### ISSUE TITLE
Confusion with Docs

### ISSUE THREAD

**Issue by pravintargaryen** [IEBH/SRA2#2]
In the docs it was mentioned that 

> SRA is built using the [PHP](http://www.php.net/) Programming language using the [CodeIgniter](http://ellislab.com/codeigniter) framework, [MySQL](https://www.mysql.com/) database storage as well as specially developed modules for [importing and exporting EndNote reference libraries](https://github.com/hash-bang/PHP-EndNote)

But the setup mentions Node.js & Gulp

> Install MongoDB
run npm ci
run gulp db
run gulp

Maybe it's just me if I have missed something

**Comment by hash-bang** [comment]
Ah yes. Apologies. I suspect that bit of the README was copy/pasted from the _original_ [SRA project](https://github.com/IEBH/SRA) which was indeed written in PHP.

I'll update the README to change that. Thanks for the feedback.

On a separate note you might want to check out [TERA-tools](https://tera-tools.com) our new SRA-with-projects upgrade. Please reach out to me if you have any questions with it.

**Comment by pravintargaryen** [comment]
Sure @hash-bang
